### ISSUE TITLE
Add support for scope

### ISSUE THREAD

**Issue by rosieks** [rebus-org/Rebus.ServiceProvider#11]
It looks that Rebus.ServiceProvider does not support correctly `AddScoped` method. Right now there is no difference betweeen using `AddScoped` and `AddSingleton`. I would expect that `AddScoped` means that some class is resolved once per message.

**Comment by trreeves** [comment]
To achieve handler instances per message, use a `Transient` lifestyle, which I think makes sense.

What value does supporting `Scoped` add?

**Comment by rosieks** [comment]
Suppose that I have message handler that depends on class A and B. And both this classes depends on DbContext. I want that both this classes share the same DbContext. In order to do that I register DbContext as Scoped. 

Also now it is confusing that in asp.net when I register something as scoped then it's resolved per request and here it is a singleton.

**Comment by trreeves** [comment]
Aah yes, that sounds useful....and the default ServiceProviderEngineScope will do the same disposing of the handlers.

So with Transient registered handlers, their lifestyle would still behave as expected right?  And get disposed by the scope.

**Comment by rosieks** [comment]
Exactly, ServiceProviderEngineScope will dispose all IDiposable objects that where resolved, so in case of my example also `DbContext` will be disposed.

**Comment by xhafan** [comment]
The current implementation which creates the scope in [NetCoreServiceProviderContainerAdapter](https://github.com/rebus-org/Rebus.ServiceProvider/blob/master/Rebus.ServiceProvider/NetCoreServiceProviderContainerAdapter.cs#L43) does not work in my scenario. In my scenario, I use [Rebus.UnitOfWork](https://github.com/rebus-org/Rebus.UnitOfWork), where in the _unitOfWorkFactory_ method I create a database transaction wrapped in an `IUnitOfWork` service, which should have scoped lifestyle, and which could be injected into other services which would share the database transaction. The problem is that the _unitOfWorkFactory_ method is called first with no scope created yet, after that the scope is created by NetCoreServiceProviderContainerAdapter. I think it should be the other way around - first, the scope should be created, and then the scope should be passed into the _unitOfWorkFactory_ method. 

Example: currently I use Castle Windsor with Rebus which works fine for me. Here is the [console app](https://github.com/xhafan/legacy-to-coreddd/blob/master/src/ServiceApp/Program.cs), and here is the _unitOfWorkFactory_ method [RebusUnitOfWork.Create](https://github.com/xhafan/coreddd/blob/master/src/CoreDdd.Rebus.UnitOfWork/RebusUnitOfWork.cs#L38). The console app using the ServiceProvider, which didn't work for me, is [here](https://github.com/xhafan/legacy-to-coreddd/blob/1e57c70ee7ee0c6a76ae998254ef1acfb558d48a/src/ServiceApp/Program.cs). As mentioned above, the `RebusUnitOfWork.Create` is called first before the scope is created, but that method should create a scoped `IUnitOfWork`.

My feeling is that [Rebus.UnitOfWork](https://github.com/rebus-org/Rebus.UnitOfWork) and [Rebus.ServiceProvider](https://github.com/rebus-org/Rebus.ServiceProvider) are not friends yet.

**Comment by Liero** [comment]
I also vote for this. Actually I believe this should be labeled as a bug.

In asp.net core the behavior is:
- Singleton - one instance per application lifetime
- Scoped - one instance per request
- Transient - new instance each time

I believe the only reasonable equivalent for Rebus is:
- Singleton - one instance per bus lifetime
- Scoped - one instance per message
- Transient - new instance each time

I can't imagine scenario, where scope would be expected to end after the handlers are created but before they are invoked.

My scenario is similar to @xhafan's

1. create single DbContext per message
2. invoke all message handlers using the DbContext instance
3. call DbContext.SaveChanges() once per Message after all handlers are invoked.

**Comment by mookid8000** [comment]
A change was introduced recently, which I believe fixes this.

Please check out Rebus.ServiceProvider 5.0.1, which will resolve handlers from a lifetime scope scoped to the incoming step context.

It also supports providing the scope manually, so that incoming pipeline steps earlier in the pipeline may create the scope and have it used throughout.
